name: Prepare Release (Reusable)

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo to access bot_mapping.json
      - name: Checkout repository
        uses: actions/checkout@v4

      # Read and base64 encode bot_mapping.json
      - name: Encode bot_mapping.json
        id: encode_bot_mapping
        run: |
          BOT_MAPPING_B64=$(base64 -w 0 bot_mapping.json)
          echo "BOT_MAPPING_B64=$BOT_MAPPING_B64" >> $GITHUB_OUTPUT

      # Call the reusable workflow in another repo
      - name: Call reusable workflow
        uses: timkrieg1/cognigy-ci-cd-pipeline/blob/main/.github/workflows/prepare_release.yaml@main
        with:
          repository: ${{ github.repository }}
          bot_mapping_b64: ${{ steps.encode_bot_mapping.outputs.BOT_MAPPING_B64 }}
        secrets: 
          pat_token: ${{ secrets.PAT }}
